spring.datasource.url=${DB_URL:jdbc:sqlserver://VerDenovo.mssql.somee.com:1433;databaseName=VerDenovo;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:fernando14112008@gmail.com}
spring.datasource.password=${DB_PASSWORD:12345678f}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.port=8080

jwt.secret=${JWT_SECRET:VerdNovo_K3y_S3cur4_2024_xZ9mP2qR7nL5wT8vA1bC6dE0fG4hI3jK}
jwt.expiration=18000000

admin.email=${ADMIN_EMAIL:vitorhugobate@gmail.com}
admin.senha=${ADMIN_SENHA:123456789Vi}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:contareservadofe@gmail.com}
spring.mail.password=${MAIL_PASSWORD:vzhmplrbgdkyyled}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-url=${FRONTEND_URL:}
